### ISSUE TITLE
Error Lesson 2 Sending-and-Receiving-data

### ISSUE THREAD

**Issue by srj1970** [PacktPublishing/The-Essential-Guide-to-Creating-Multiplayer-Games-with-Godot-4.0#1]
Tested on two computers (Using debug 2 instances on each).  If user password entered, and password does not match dictionary entry, Godot Debug window freezes.  "Invalid operands 'String' and 'Nil' in operator in. LoginScreen.gd Line 55.  F.Y.I. Thanks.

**Comment by henriiquecampos** [comment]
Fixed in https://github.com/PacktPublishing/The-Essential-Guide-to-Creating-Multiplayer-Games-with-Godot-4.0/commit/6e8c7b9b547e501988106314aec45d8037a1fe27, closing the issue
